### PR TITLE
Merge similar strings

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Merge strings in https://github.com/futtta/autoptimize/blob/master/classlesses/autoptimizeCacheChecker.php#L45 and https://github.com/futtta/autoptimize/blob/master/classlesses/autoptimizeCacheChecker.php#L61

### CODE REVIEW

**Comment by futtta** [comment]
hmmm, not sure here @pedro-mendonca:
1. The default content type of wp_mail is ‘text/plain’ which does not allow using HTML, so the HTML-tags you introduce will not work
2. your description mentions merging strings on L45 and L61, but I don't see that in the actucal code?

**Comment by pedro-mendonca** [comment]
1. Ok, I didn't thought about the plain text issue. You're right.
2. I see the strings here in both link, and they're pretty much the same, appart from the html formatting.

**Comment by futtta** [comment]
for (2); you're right, but you're not fixing that in your PR, as I only see the `$ao_mailbody=`-line changed?

**Comment by pedro-mendonca** [comment]
Yes, I only changed that one assuming to make it similar to the one in L61.
But don't bother, this doesn't make sense to merge since one must be plain text and the other have HTML.

**Comment by futtta** [comment]
closing, but thanks for your input @pedro-mendonca, don't hesitate to continue looking for area's in which AO can improve!

**Pull request closed without merging**
