### PR TITLE
Static Analysis fixes

### PR DESCRIPTION
**Pull request by szepeviktor**
@futtta You find the test tool here https://github.com/szepeviktor/autoptimize/commit/1644b182c11523c797b9fc507090bf4182fca083

### CODE REVIEW

**Comment by szepeviktor** [comment]
This is Level 0.
You are free to continue static analysis on higher levels!

**Comment by szepeviktor** [comment]
Could you take a look at the CDN test?

**Comment by futtta** [comment]
hey @szepeviktor I just synced "master" with the 2.5 codebase (which i released earlier today), could you look into the conflict above? also the travis tests are failing, might be because you force a different wordpress version resulting in different hashes for the autoptimized files?

**Comment by szepeviktor** [comment]
> might be because you force a different wordpress version resulting in different hashes for the autoptimized files

Okay, I've reviewed the 8 changes in this PR but I do not understand which is related to WP version. Could you help me?

**Comment by futtta** [comment]
"all checks have passed" and " no conflicts with the base branch, so that hurdle has been taken. i'll review more in detail tomorrow Viktor :-)

@zytzagoo in case you have time and you're interested feel free to chime in!

**Comment by szepeviktor** [comment]
@futtta Thank you for merging.

Are interested adding static analysis to TravisCI?

**Comment by futtta** [comment]
why not :)

**Pull request merged**
