### PR TITLE
Add Autoptimize compatibility with Multisite

### PR DESCRIPTION
**Pull request by juanfran-granados**
Hello,

This is Juanfran Granados from [Mirai](https://www.mirai.com/), an hotelier agency. This month we were evaluating your terrific plugin to handle static resources optimization, and we found out that your plugin does not have a global configuration for WordPress Multisite:

https://wordpress.org/support/topic/globally-configure-for-multisite/

Yes, you can copy the configuration to each site, but that solution does not cover a change in configuration in the future.

I addressed this problem modifying your code to use a wrapper for get_option and update_option. Inside of that wrapper, I took care of the standalone and multisite cases. I tought it is a cleaner option than adding if/else clauses in each get_option and update_option of your code. Feel free to reformulate it.

Also, I've filtered the update_option logic using pre_update_option hook to check if it's a multisite instance. I was forced to do that because you are using the Settings API to save your admin form and I didn't find a way to create a clean separate logic for Multisite.

Thanks!

### CODE REVIEW

**Comment by futtta** [comment]
Wow, that would be a great addition @juanfran-granados , thanks for the work you did on this!

The [mulitisite-tests on Travis-ci seem to fail](https://travis-ci.org/futtta/autoptimize/builds/533692228) with this error however;

> Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /home/travis/build/futtta/autoptimize/classes/autoptimizeOption.php on line 32

Problem might be similar to what [I encountered/ fixed earlier for is_plugin_active](https://github.com/futtta/autoptimize/commit/5dbb402707d0daf1cd9ebaf26fe1cad81e33a36f)?

**Comment by juanfran-granados** [comment]
Ooops! Ok, let's see if including the plugin.php file works...

**Comment by juanfran-granados** [comment]
Done :) Thanks.

**Comment by futtta** [comment]
Thanks! I'll first push out AO 2.5.1 and will then probably test myself and
then merge in the beta-branch.

Some questions:
* Based on my reading of the code, if AO is network activated then the AO
settings won't be shown on subsites any more, only on the main one?
* What would happen if this got installed on an existing multisite install
where subsites are already configured?

**Comment by juanfran-granados** [comment]
Hello Frank,

Great news! Of course, test it yourself and ask me anything you need. Regarding your questions:

> * Based on my reading of the code, if AO is network activated then the AO
settings won't be shown on subsites any more, only on the main one?

Yes, that's correct. Also the get_option fetches the configuration from the network settings.

> * What would happen if this got installed on an existing multisite install
where subsites are already configured?

If you have subsites configured and the plugin is not active network wide, it will get the configuration from the subsite. But if you activate the plugin in the whole network, then the network settings will be the ones used.

**Comment by futtta** [comment]
So how would you feel about adding an option on the network-wide page which
tells AO to show and use the network-wide or the child-sites config?

And while we're at it; adding a simple "ask your network admin"-page to
child-site admins if network-wide config is uses? :-)

**Comment by juanfran-granados** [comment]
> So how would you feel about adding an option on the network-wide page which tells AO to show and use the network-wide or the child-sites config? 

Nice idea! I will try to get that done next week.

> And while we're at it; adding a simple "ask your network admin"-page to child-site admins if network-wide config is uses? :-)

In my opinion, I would prefer to remove the admin menu in child-sites if network-wide configuration is in use. But if you are 100% sure of it, I could maintain the child-site admin menu, outputting "ask your network admin". It's better if you add the HTML+CSS layer on top of that, since I don't know what you have in mind.

**Comment by futtta** [comment]
great juanfran, looking forward to that! :-)

**Comment by futtta** [comment]
hey @juanfran-granados how are things going? :-)

**Comment by juanfran-granados** [comment]
Hello @futtta, I'm pretty busy these days, but I have more or less 50% done. I'll upload the improvements as soon as I can, previously tested on multisite and standalone instances.

**Comment by futtta** [comment]
No need to rush, just being curious :)

**Comment by futtta** [comment]
Hey @juanfran-granados how are things going? Have you already found some time to work on this a bit  more? :)

**Comment by juanfran-granados** [comment]
Hello @futtta, just getting in touch with this code again :)

I am really busy these days, but I will get two hours a week to get this done. I will upload the modifications as soon as I have them. If you are willing to go faster on this, feel free to implement this by yourself.

**Comment by futtta** [comment]
No worries, have a ton of stuff on my to do list for AO26 myself as well :)

**Comment by juanfran-granados** [comment]
Hello @futtta! I've been able to get some hours to finish what was pending. Recap:

> So how would you feel about adding an option on the network-wide page which tells AO to show and use the network-wide or the child-sites config?

Done, you can see the option only in the network admin configuration page.

> And while we're at it; adding a simple "ask your network admin"-page to child-site admins if network-wide config is uses? :-)

Done. I've built another function for that output (show_message in classes/autoptimize_Config.php). As we discussed, feel free to change the output and the styles. I18n is not being handled yet.

Let's see if it pass the CI checks :)

**Comment by futtta** [comment]
Wow, great job JuanFran, looking forward to taking this out for a spin! More news the next couple of days :-)

**Comment by futtta** [comment]
Sorry to be a pain in the butt @juanfran-granados (you've done a great job already), but could you make a PR against the beta branch iso the master one?

**Pull request merged**
