### PR TITLE
Properly decode Google Font urls

### PR DESCRIPTION
**Pull request by nextend**
https://wordpress.org/support/topic/bug-in-google-fonts-async-mode/

### CODE REVIEW

**Comment by futtta** [comment]
Thanks @nextend 

Now as the problem is specific the webfont-js implementation it might be preferable to make a similar change around https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeExtra.php#L296 ?

**Comment by nextend** [comment]
@futtta Yeah, but it might be better to decode as soon as possible and encode again in other places. It might be much more future proof.

For example:
`                $fonts_markup = '<link ' . $rel_string . ' id="ao_optimized_gfonts" href="https://fonts.googleapis.com/css?family=' . $fonts_string . '" />';`

Would become:
`                $fonts_markup = '<link ' . $rel_string . ' id="ao_optimized_gfonts" href="' . esc_url_raw(add_query_arg( 'family', $fonts_string, 'https://fonts.googleapis.com/css' )) . '" />';`

What do you think?

**Comment by futtta** [comment]
I'm more of a "the smallest fix possible"-type-a-guy, but I could live with
that ;-)

**Comment by nextend** [comment]
@futtta, Okay, I can live with local changes. What do you think about the following?

```
$fonts_array = array_map('fonts_array', $fonts_array);

$fonts_markup = '<script data-cfasync="false" id="ao_optimized_gfonts" type="text/javascript">WebFontConfig={google:{families:' . wp_json_encode($fonts_array) . ' },classes:false, events:false, timeout:1500};</script>';
```

I haven't tested it as I'm out of office, but it should work. Will try tomorrow.

**Comment by futtta** [comment]
looking forward to that @nextend :)

**Comment by nextend** [comment]
Okay, I updated my pull request. I missed one line, I'm not sure why it was there. Was it a fix for a previous bug?

`$fonts_markup  = trim( trim( $fonts_markup, "'" ), ',' );`

**Comment by futtta** [comment]
that line was to remove `'` or `,` in the foreach-loop before, your json_encode solution is more elegant and does not need that "cleanup" :-)

**Pull request merged**
