### PR TITLE
Move examples to README

### PR DESCRIPTION
**Pull request by szepeviktor**
+ proper PHP-doc

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please also consider WP code styling
https://make.wordpress.org/core/handbook/coding-standards/php/

**Comment by szepeviktor** [comment]
You can even insert `## Javascript` and `## CSS` sections.

**Comment by szepeviktor** [comment]
> Copy it to /wp-content/plugins/autoptimize_helper.php and activate it in WordPress' plugin page. After that you can simple remove the one of the comment-sequences (double-slash) to activate one (or more) of the functions in there.

Oops! Was it a real plugin-stub?

**Comment by futtta** [comment]
yep, it is :-)

**Comment by szepeviktor** [comment]
Anyway you can add it to the README.
I think PHP-doc looks famliar to the PHP-trained eye.

**Comment by futtta** [comment]
thanks for that :-)

**Pull request merged**
