### PR TITLE
Allow third-party plugins to filter cache url's

### PR DESCRIPTION
**Pull request by shakee93**
This commit allows third party plugins to provide an updated/altered/modified versions of autoptimize files to hook in.

### CODE REVIEW

**Comment by futtta** [comment]
Can you explain what you would want to do here? Because changing the filename with the filter will break things, as $this->filename (which is set in the `__construct` will remain unaltered and hence the filtered URL's (which ends up in the HTML) will point to resources that don't exist?

**Comment by shakee93** [comment]
i am building a plugin which only extracts used css. ill be scraping the pages and creating copies of cleaned css files for each page. the `getname` function is used to set the url's on elements. ill be replacing the url's with cleaned css url's. which makes sites much more faster and lightweight.

**Comment by futtta** [comment]
Interesting! :-)

The problem is that the filter is supposed to have the full URL to the autoptimized CSS/ JS (so with `AUTOPTIMIZE_CACHE_URL`) , which in your commit isn't the case anymore and that would break e.g. Cloudflare hooking into that filter to know what files to HTTP/2 push :-/

**Comment by futtta** [comment]
What you could do, alternatively, is hooking into `autoptimize_html_after_minify` which gives you the full HTML (as you're "scraping" anyway) and out of which you could parse & replace the autoptimized CSS/ JS URL's?

**Comment by shakee93** [comment]
That's a good idea as well. but we will have to do alot of work scraping the html and parsing the css files. it would be much easier if we could do it with the filename filter. 

my bad i thought about it later. maybe we could add a new filter `autoptimize_filter_cache_getfilename` like in the below example ? that would not break anything and would allow people to change file url.

```php
public function getname()
{
     // lets keep this this way
     apply_filters( 'autoptimize_filter_cache_getname', AUTOPTIMIZE_CACHE_URL . $this->filename );

     return apply_filters( 'autoptimize_filter_cache_getfilename', $this->filename );
}
```

what do you think ?

**Comment by futtta** [comment]
Hmm, would like to avoid that to be honest ..

Maybe using `autoptimize_filter_cache_getname` filter to get the full paths to the AO'ed files and then use `autoptimize_html_after_minify` to replace those paths with your new ones?

**Comment by shakee93** [comment]
Hey its okey !! ill try that workaround !! Thank you for this AWESOME PLUGIN !! ♥

**Comment by futtta** [comment]
Most welcome Shakeeb, feel free to keep me posted about your progress! :)

**Comment by shakee93** [comment]
Sure thing ill keep you posted !! 😍

**Pull request closed without merging**
