### PR TITLE
Merge AO Multisite to beta branch

### PR DESCRIPTION
**Pull request by juanfran-granados**
Hello @futtta! Here we go again :)

- I've merged the changes to the new beta branch.
- I've manually tested in a standalone site and multisite instance.
- I've passed the tests locally.
- I've followed the WP coding standards as much as I can. I leave to you changing the indentation, choosing how to escape output and changing class names and filenames.

Have a good weekend!

PS: You can delete the other PR.

### CODE REVIEW

**Comment by futtta** [comment]
[the CI-tests failed](https://travis-ci.org/futtta/autoptimize/builds/587422432) @juanfran-granados , could you check?

**Comment by juanfran-granados** [comment]
I'm on it, let's see now.

**Comment by futtta** [comment]
fixed, thanks :-)

**Comment by juanfran-granados** [comment]
:+1:

**Pull request merged**
