### PR TITLE
Don't attempt CDN URL replacement on embedded data strings

### PR DESCRIPTION
**Pull request by JeffPyeBrook**
Filter processing routines should have to check if the URI is embedded data prior to replacing

### CODE REVIEW

**Comment by futtta** [comment]
not too sure Jeff; the images are extracted from the CSS on https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeStyles.php#L300 and this rexeg already explictly excludes embedded data?

frank

**Comment by JeffPyeBrook** [comment]
I am also puzzled why it was happening, but I was seeing the embedded image show up in the filter callback. 

If you want to try it out, this is the CDN plugin I use
https://github.com/JeffPyeBrook/wp-cdn-rewriter

To set it up:
Drop the php into wp-content/mu-plugins 
Create a CNAME to like cdn.mytestsite.com back to www.mytestsite,com
Add the PBCI_CDN_FROM and PBCI_CDN_TO defines to your wp-config.php 

It should just work. 

Set a breakpoint at line 445, you will hit it if you have embedded data

**Comment by futtta** [comment]
I've dived in and the problem was not all data-uri's were excluded;
`url(data:`
was excluded, but
`url("data:`
or
`url (data:`
(and variations) were not.

I updated the regex to take those into account as well, which _should_ remove the need for the extra check you proposed in the above pull request.

Can you test this commit?

frank

**Comment by JeffPyeBrook** [comment]
Sure thing. I'll check it tomorrow.

**Comment by futtta** [comment]
did you already have a chance to test that commit (improved regex to exclude data:) Jeff?

**Comment by JeffPyeBrook** [comment]
I have been running it on my development site for a little bit and haven't seen any "data:image" uri leak through.

**Comment by futtta** [comment]
great! in that case I'm just going to close (and not merge your pull request) Jeff. thanks for the valuable feedback!!

**Comment by JeffPyeBrook** [comment]
perfect! 

The cdn plugin I referenced above works well with autoptimize, if anyone is looking for something feel free to point them to it. 

The advantage to using it over the ossdl code that is in wp-super-cache is that it doesn't capture the full output buffer for processing. Can save as much as a couple hundred milliseconds per page request on moderately powered servers.

**Pull request closed without merging**
