### PR TITLE
Add Portuguese (pt_PT) translation

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by futtta** [comment]
thanks, but I see you're also the main (and only) contributor here; https://translate.wordpress.org/locale/pt/default/wp-plugins/autoptimize

so is it useful to still add the file here as well?

**Comment by pedro-mendonca** [comment]
Hi,
I already did it, in translate.wp.org but the strings aren't updated with the latest changes.
I also pushed it here because you also keep language files in the repo, so I assumed you want you want it, still I use to keep this local files as it is easier to translate and debug strings, as I did with Autoptimize.
Feel free to use it or not :)

**Comment by futtta** [comment]
hmmm, as i've removed most translations from AO proper if one is availble from the translation theme, i'll not re-add it here now. but do ask the portuguese translation team to approve your changes :-)

**Comment by pedro-mendonca** [comment]
It's approved directly, as I'm an editor.
I'll wait for the reviewed strings to upload the last ones.

**Pull request closed without merging**
