### PR TITLE
Filter: Allow moving inline scripts before or after the concattenated script

### PR DESCRIPTION
**Pull request by mehigh**

### CODE REVIEW

**Comment by mehigh** [comment]
I've added this 'autoptimize_js_move_inline' filter, which I've successfully used on a large network of sites where some plug-ins had inline scripts with dependencies for the concattenated plug-ins (some init functions were being called inline with some dynamic variables)

I've used the following to achieve a functional usage of your plug-in:

I've used the 'after' option of the filter in order to put the scripts after the concatenated file:
`add_filter('autoptimize_js_move_inline', function () { return 'after'; } );`

I had to discard the defer in order for the browser to parse the file before running the inline scripts which needed functions defined in it: 
`add_filter('autoptimize_filter_js_defer', function () { return false; } );`

This new PR is spun off from our discussion held in #65 

Thank you for an awesome plug-in!

**Comment by futtta** [comment]
Nice @mehigh 

I would like to propose 2 last changes;
* rename the filter into autoptimize_js_moveable, as it would not apply to inline alone but tot all non-aggregated JS
* add $tag as 2nd argument in the apply_filter, so we can -if we would want to-  make the function hooked into this do conditional stuff based on the $tag (to move some scripts last and some first and some not at all)

What do you think? :-)

**Comment by mehigh** [comment]
Thank you for the feedback, @futtta 

I'll make the necessary changes with the rename. 
I'll investigate how $tag is used elsewhere in the plug-in in order to maintain the same standards with this 2nd parameter. I assume it's fine to maintain the 'first' and 'last' string as the first parameter for this filter.

**Comment by futtta** [comment]
for the 2nd parameter, cfr. https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeScripts.php#L24 but instead of `$this->content` just pass `$tag`

**Comment by mehigh** [comment]
@futtta 

I've renamed the filter and added that 2nd optional $tag parameter. I've tested this to be functioning well with a filter like in the readme (with either 'first' or 'last' as parameters).
Does the readme need to contain an example with the optional parameter as well, or that's only for advanced users diving into code?

**Comment by futtta** [comment]
this is for advanced users indeed, readme.md is far from complete anyhow ;-)

**Pull request merged**
