### PR TITLE
Alternative to define nonce value on page

### PR DESCRIPTION
**Pull request by pablocusto**
What do you think adding the nonce value in the autoptimize_ajax_object instead of adding it as a class name? It will be a little safer or is the same?

### CODE REVIEW

**Comment by pablocusto** [comment]
Sorry, I was wrong. I think I made changes to the Master.

**Comment by pablocusto** [comment]
Oh! No, the point is I did not have my fork synchronized with the Master .. I think ... I thought that was done synchronized automatically.
Mmm...  What is the way to synchronize the fork of one has when the master is updated? (Excuse my ignorance)

**Comment by futtta** [comment]
afraid I'm not a git(hub) expert either @pablocusto ... but passing the nonce in the ajax-object definitively is a better solution! :)

**Comment by futtta** [comment]
As;
> This branch has conflicts that must be resolved

and as I'm not a Git(hub)-expert myself, I applied your changes manually on my dev-machine and will commit them to my Github repo.

your solution indeed makes **_a lot_** more sense @pablocusto, again thanks for your contribution!

**Pull request closed without merging**
